import { AiFillStar } from "react-icons/ai";

export const flash = [
    {
      id:1,
      img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
      title: "Nike Air Monarch IV",
      star: <AiFillStar className="rating-star" />,
      reviews: 123,
      prevPrice: 140,
      newPrice: 200,
      company: "Nike",
      color: "white",
      category: "sneakers"
    },
    {
      id:2,
      img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
      title: "Nike Air Vapormax Plus",
      star: <AiFillStar className="rating-star" />,
      reviews:123,
      prevPrice: 140,
      newPrice: 200,
      company: "Nike",
      color: "red",
      category: "sneakers",
    },
  
    {
      id:3,
      img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
      title: "Nike Waffle One Sneaker",
      star: <AiFillStar className="rating-star" />,
      reviews: 123,
      prevPrice: 140,
      newPrice: 200,
      company: "Nike",
      color: "green",
      category: "sneakers",
    },
    {
      id:42,
      img: spraysetImage,
      title: "Curology Product Set",
      star: <AiFillStar className="rating-star" />,
      reviews: 145,
      prevPrice: 200,
      newPrice: 175,
      company: "Curology",
      color: "white",
      category: "cosmetics",
    },
    {
      id:43,
      img:toycarImage,
      title: "Kids Electric Car",
      star: <AiFillStar className="rating-star" />,
      reviews: 65,
      newPrice: 960,
      company: "Harvet",
      color: "red",
      category: "electronics",
    },
    {
      id:44,
      img: tvImage,
      title: "OPS LCD Gaming Monitor",
      star: <AiFillStar className="rating-star" />,
      reviews: 105,
      prevPrice: 1120,
      newPrice: 1000,
      company: "Samsung",
      color: "black",
      category: "electronics",
      
    },
    {
      id:4,
      img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
      title: "Nike Running Shoe",
      star: <AiFillStar className="rating-star" />,
      reviews: 123,
      prevPrice: 140,
      newPrice: 200,
      company: "Adidas",
      color: "black",
      category: "sneakers",
    },
    {
      id:5,
      img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
      title: "Flat Slip On Pumps",
      star: <AiFillStar className="rating-star" />,
      reviews: 123,
      prevPrice: 140,
      newPrice: 200,
      company: "Vans",
      color: "green",
      category: "flats",
    },
    {
      id:6,
      img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
      title: "Knit Ballet Flat",
      star: <AiFillStar className="rating-star" />,
      reviews:123,
      prevPrice: 140,
      newPrice: 50,
      company: "Adidas",
      color: "black",
      category: "flats",
    },
    {
      id:41,
      img: speakerImage,
      title: "RGB Liquid CPU cooler",
      star: <AiFillStar className="rating-star" />,
      reviews: 85,
      prevPrice: 170,
      newPrice: 160,
      company: "AK-Tech",
      color: "black",
      category: "electronics",
    },
  ]